name: Documentation

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build_and_deploy_docs:
    name: Documentation Building and Deployment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_TOKEN }}
          path: sparsembar

      - name: Additional info about the build
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a

      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '1.5.1-0'
          environment-file: sparsembar/devtools/conda-envs/docs_env.yaml
          environment-name: docs
          create-args: >-
            python=3.9

      - name: Install package
        shell: bash -l {0}
        run: |
          cd sparsembar/
          pip install .
          micromamba list

      - name: Build Documentation
        shell: bash -l {0}
        run: |
          cd sparsembar/
          sphinx-build ./docs ./html

      - name: Run tests
        shell: bash -l {0}
        run: |
          cd sparsembar/
          pytest

      - name: Get coverage report
        id:  coverage
        shell: bash -l {0}
        run: |
          cd sparsembar/
          COVERAGE=$(coverage report | tail -1 | awk '{print $4}')
          OFFSET=$(((${COVERAGE::-1}-35)/6-1))
          [[ $OFFSET < 0 ]] && OFFSET=0
          PALETTE="000111222333"
          CODE=${PALETTE:$OFFSET:3}
          COLOR=$(echo $CODE | sed -e "s/0/red,/g; s/1/orange,/g; s/2/yellow,/g; s/3/green,/g; s/,$//")
          echo "coverage=${COVERAGE}" | tee -a "${GITHUB_OUTPUT}"
          echo "color=${COLOR}" | tee -a "${GITHUB_OUTPUT}"

      - name: Generate coverage badge
        uses: emibcn/badge-action@v2.0.2
        with:
          label: 'Coverage'
          label-color: 'black'
          status: ${{ steps.coverage.outputs.coverage }}
          color: ${{ steps.coverage.outputs.color }}
          path: 'sparsembar/htmlcov/coverage.svg'

      - name: Deploy documentation
        shell: bash -l {0}
        run: |
          if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
            echo "Deployment is deactivated on pull requests"
          else
            cd sparsembar/
            git reset --hard HEAD
            set -x
            echo "::group::Push page to gh-pages branch"
            git config user.name "$(git show --format=%an -s)"
            git config user.email "$(git show --format=%ae -s)"
            git fetch origin
            git switch gh-pages
            rsync -va --delete-excluded html/ docs/
            rsync -va --delete-excluded htmlcov/ docs/coverage/
            touch docs/.nojekyll
            git add -f docs/*
            git add -f docs/.nojekyll
            git add -f docs/coverage/*
            git commit -m "Docs from $GITHUB_REF $GITHUB_SHA" || echo "Branch is up to date"
            git push -f origin gh-pages
            echo "::endgroup::"
          fi

      - uses: actions/checkout@v3
        with:
          repository: craabreu/badges
          token: ${{ secrets.REPO_TOKEN }}
          path: badges
          fetch-depth: 0

      - name: Deploy coverage badge
        shell: bash -l {0}
        run: |
          if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
            echo "Deployment is deactivated on pull requests"
          else
            echo "::group::Push coverage badge to public repo"
            BRANCH=CkbOTqKthJ
            DATETIME=$(date +"%D at %T.%6N")
            cd badges
            git checkout $BRANCH
            cp -f ../sparsembar/htmlcov/coverage.svg ./
            git add -f ./coverage.svg
            git config user.name "$(git show --format=%an -s)"
            git config user.email "$(git show --format=%ae -s)"
            git commit -m "Created on $DATETIME" || echo "Branch is up to date"
            git push -f
            echo "::endgroup::"
          fi
